// Copyright 2014 The lime Authors.
// Use of this source code is governed by a 2-clause
// BSD-style license that can be found in the LICENSE file.

// This package creates sublime module for python plugins
//
// Most of the code here is generated by tasks/local/build/gen_python_api.go
// and should not be changed manually.
//
package api
